export const QUERY_KEYS = {
    GET_ALL_SUBJECT_LIST:"GET_ALL_SUBJECT_LIST",
    GET_ALL_CATEGORY_LIST:"GET_ALL_CATEGORY_LIST",
    GET_ALL_CITY_LIST:"GET_ALL_CITY_LIST",
    GET_ALL_LOCATION_LIST:"GET_ALL_LOCATION_LIST",
    GET_ALL_GUARDIAN_LIST:"GET_ALL_GUARDIAN_LIST",
    GET_ALL_TUTOR_LIST:"GET_ALL_TUTOR_LIST",
    GET_ALL_TUTOR_REQUEST_LIST:"GET_ALL_TUTOR_REQUEST_LIST"
}